config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_items, :path => 'portfolio'
  get 'stock_signal_checks/index'
  get 'stock_signals/index(/:check_id)', to: 'stock_signals#index', as: 'stock_signals'
  get 'stock_signals/full(/:check_id)', to: 'stock_signals#full', as: 'stock_signals_full'
  get 'stock_signals/compact(/:check_id)', to: 'stock_signals#compact', as: 'stock_signals_compact'
  resources :stocks
  root to: 'stock_signals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock_signal_check.rb
class StockSignalCheck < ApplicationRecord
  has_many :stock_signals, dependent: :destroy
end

app/controllers/stock_signal_checks_controller.rb
class StockSignalChecksController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
  end
end

app/helpers/stock_signal_checks_helper.rb
module StockSignalChecksHelper
end

app/views/stock_signal_checks/index.html.erb
<div class='container-fluid'>
  <h2 class='pt-4'>Check di Segnali </h2>
  <hr>
  <div class='row'>
    <%= content_tag 'table', id: 'checks',class: 'table table-striped datatable' do %>
      <thead>
        <tr>
          <th>Id</th>
          <th>Data Creazione</th>
          <th>Data Aggiornamento</th>
        </tr>
      </thead>
      <tbody>
        <% @stock_signal_checks.each do |c| %>
          <tr>
            <td><%= link_to c.id, stock_signals_path(check_id: c.id) %></td>
            <td><%= link_to(l(c.created_at, format: "%d-%m-%Y %H:%M"), stock_signals_path(check_id: c.id)) %></td>
            <td><%= link_to(l(c.updated_at, format: "%d-%m-%Y %H:%M"), stock_signals_path(check_id: c.id)) %></td>
          </tr>
        <% end -%>
      </tbody>
    <% end %>
  </div>
  <hr>
</div>