config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_items, :path => 'portfolio'
  get 'stock_signal_checks/index'
  get 'stock_signals/index(/:check_id)', to: 'stock_signals#index', as: 'stock_signals'
  get 'stock_signals/full(/:check_id)', to: 'stock_signals#full', as: 'stock_signals_full'
  get 'stock_signals/compact(/:check_id)', to: 'stock_signals#compact', as: 'stock_signals_compact'
  resources :stocks
  root to: 'stock_signals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock_signal.rb
class StockSignal < ApplicationRecord
  enum suggestion: [ :buy, :sell ]
  enum level: [ :low, :medium, :high ]
  belongs_to :stock
  belongs_to :stock_signal_check
end

app/controllers/stock_signals_controller.rb
class StockSignalsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_stock_signals

  def index
    if session[:view_format] == "full"
      redirect_to :action => "full", :check_id => params[:check_id]
    elsif session[:view_format] == "compact"
      redirect_to :action => "compact", :check_id => params[:check_id]
    else
      render :action => "full"
    end
  end

  def full
    session[:view_format] = "full"
  end

  def compact
    session[:view_format] = "compact"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_signals
      if params[:check_id]
        @stock_signal_check = StockSignalCheck.find(params[:check_id])
      else
        @stock_signal_check = StockSignalCheck.last
      end
      @signals = @stock_signal_check.stock_signals
    end

end

app/helpers/stock_signals_helper.rb
module StockSignalsHelper
end

app/views/stock_signals/compact.html.erb
<div class='container-fluid'>
  <h2 class='pt-4'>Segnali del <%= l @signals.first.stock_signal_check.updated_at, format: "%d-%m-%Y %H:%M" %></h2>
  <%= link_to "vista completa", stock_signals_full_path(check_id:  @signals.first.stock_signal_check.id) %>
  <hr>
  <div class='row'>
    <%= content_tag 'table', class: 'table table-striped datatable' do %>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Quotazione chiusura</th>
          <th>Segnale</th>
          <th>Suggerimento</th>
          <th>Rendimento netto</th>
          <th>Min-Max Anno</th>
          <th>Volatilità</th>
          <th>Dividendo</th>
        </tr>
      </thead>
      <tbody>
        <% @signals.each do |s| %>
          <tr>
            <td><%= link_to s.stock.name, s.stock %></td>
            <td><%= "#{s.quotation} (#{l s.quotation_date, format: "%d-%m"})" %></td>
            <td><%= s.description %></td>
            <td><%= content_tag :p, "#{s.suggestion} #{s.level}", class: "suggestion #{s.suggestion}-#{s.level}"  %></td>
            <td><%= number_to_percentage(s.dividend_yield*100, precision: 2) %></td>
            <td><%= "#{s.min_year}-#{s.max_year}" %></td>
            <td><%= number_to_percentage(s.volatility*100, precision: 2) %></td>
            <td><%= s.stock.dividend %></td>
          </tr>
        <% end -%>
      </tbody>
    <% end %>
  </div>
  <hr>
</div>

app/views/stock_signals/full.html.erb
<div class='container-fluid'>
  <h2 class='pt-4'>Segnali del <%= l @signals.first.stock_signal_check.updated_at, format: "%d-%m-%Y %H:%M" %></h2>
  <%= link_to "vista compatta", stock_signals_compact_path(check_id:  @signals.first.stock_signal_check.id) %>
  <hr>
  <div class='row'>
    <%= content_tag 'table', class: 'table table-striped datatable' do %>
      <thead>
        <tr>
          <th>Simbolo</th>
          <th>Nome</th>
          <th>Data quotazione</th>
          <th>Quotazione chiusura</th>
          <th>Min Anno</th>
          <th>Max Anno</th>
          <th>Volatilità</th>
          <th>Dividendo</th>
          <th>Rendimento netto</th>
          <th>Segnale</th>
          <th>Dettagli</th>
          <th>Suggerimento</th>
        </tr>
      </thead>
      <tbody>
        <% @signals.each do |s| %>
          <tr>
            <td><%= link_to s.stock.symbol, s.stock %></td>
            <td><%= link_to s.stock.name, s.stock %></td>
            <td><%= l s.quotation_date, format: "%d-%m-%Y" %></td>
            <td><%= s.quotation %></td>
            <td><%= s.min_year %></td>
            <td><%= s.max_year %></td>
            <td><%= number_to_percentage(s.volatility*100, precision: 2) %></td>
            <td><%= s.stock.dividend %></td>
            <td><%= number_to_percentage(s.dividend_yield*100, precision: 2) %></td>
            <td><%= s.description %></td>
            <td><%= s.details %></td>
            <td><%= content_tag :p, "#{s.suggestion} #{s.level}", class: "suggestion #{s.suggestion}-#{s.level}"  %></td>
          </tr>
        <% end -%>
      </tbody>
    <% end %>
  </div>
  <hr>
</div>