config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_items, :path => 'portfolio'
  get 'stock_signal_checks/index'
  get 'stock_signals/index(/:check_id)', to: 'stock_signals#index', as: 'stock_signals'
  get 'stock_signals/full(/:check_id)', to: 'stock_signals#full', as: 'stock_signals_full'
  get 'stock_signals/compact(/:check_id)', to: 'stock_signals#compact', as: 'stock_signals_compact'
  resources :stocks
  root to: 'stock_signals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :stock_signals, dependent: :destroy
  has_many :portfolio_items, dependent: :destroy, inverse_of: :stock
  validates_presence_of :symbol
  validates_uniqueness_of :symbol
  validates_presence_of :name
  validates_uniqueness_of :name

  def self.update_or_create_by(args, attributes)
    obj = self.find_or_create_by(args)
    obj.update(attributes)
    return obj
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:symbol, :name, :dividend, :market)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= bootstrap_form_for(@stock, layout: :horizontal, label_col: 'col-sm-2 col-form-label', control_col: 'col-sm-10') do |f| %>

    <%= f.text_field :symbol, label: "Simbolo" %>
    <%= f.text_field :name, label: "Nome" %>
    <%= f.number_field :dividend, label: "Dividendo", step: 0.001 %>
    <%= f.text_field :market, label: "Mercato" %>

  <div class='form-group row'>
    <div class='col-sm-2'></div>
    <div class='col-sm-10'>
      <%= f.submit 'Invia', class: 'btn btn-primary' %>
      <%= back_link class: 'btn btn-default pull-right' %>
    </div>
  </div>

<% end %>

app/views/stocks/edit.html.erb
<div class='container-fluid'>
  <h3 class='pt-4'>Editing stock</h3>
  <div class='row'>

    <div class='col-md-3'>
      <div class='list-group'>
        <%= link_to stocks_path, class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :list) %> Lista Azioni
        <% end %>
        <%= link_to @stock, class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :eye) %> Mostra Azione
        <% end %>
        <%= link_to @stock, data: {confirm: 'Are you sure?'},
              method: :delete, class: 'list-group-item list-group-item-danger list-group-item-action' do %>
          <%= icon(:fas, :trash) %> Cancella Azione
        <% end %>
      </div>
    </div>

    <div class='col-md-9'>
      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/stocks/index.html.erb
<div class='container-fluid'>
  <h2 class='pt-4'>Azioni</h2>
  <hr>
  <div class='row'>
    <%= content_tag 'table', class: 'table table-striped datatable' do %>
      <thead>
        <tr>
          <th>Simbolo</th>
          <th>Nome</th>
          <th>Quotazione</th>
          <th>Data quotazione</th>
          <th>Data check</th>
          <th>Dividendo</th>
          <th>Mercato</th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <tr>
            <td><%= link_to stock.symbol, stock %></td>
            <td><%= link_to stock.name, stock %></td>
            <td><%= stock.quotation %></td>
            <td><%= l stock.quotation_date, format: "%d-%m-%Y" unless stock.quotation_date.nil? %></td>
            <td><%= l stock.quotation_check, format: "%d-%m-%Y %H:%M" unless stock.quotation_check.nil? %></td>
            <td><%= stock.dividend %></td>
            <td><%= stock.market %></td>
          </tr>
        <% end -%>
      </tbody>
    <% end %>
  </div>
  <hr>
  <%= link_to new_stock_path, class: 'btn btn-primary btn-lg' do %>
    <%= icon(:fas, :plus) %> Nuova azione
  <% end %>
</div>

app/views/stocks/new.html.erb
<div class='container-fluid'>
  <h3 class='pt-4'>Nuova Azione</h3>
  <%= render 'form' %>
</div>

app/views/stocks/show.html.erb
<div class='container-fluid'>
  <h3 class='pt-4'>Mostra Azione</h3>
  <div class='row'>

    <div class='col-md-3'>
      <div class='list-group'>
        <%= link_to stocks_path, class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :list) %> Lista Azioni
        <% end %>
        <%= link_to edit_stock_path(@stock), class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :wrench) %> Modifica Azione
        <% end %>
        <%= link_to new_stock_path, class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :plus) %> Nuova Azione
        <% end %>
      </div>
    </div>

    <div class='col-md-9'>
      <div class='card'>
        <div class='card-header'>Dettagli</div>
        <ul class='list-group list-group-flush'>
          <li class='list-group-item'>
            <span>Simbolo: </span>
            <strong><%= @stock.symbol %></strong>
          </li>
          <li class='list-group-item'>
            <span>Nome: </span>
            <strong><%= @stock.name %></strong>
          </li>
          <li class='list-group-item'>
            <span>Quotazione: </span>
            <strong><%= @stock.quotation %></strong>
          </li>
          <li class='list-group-item'>
            <span>Data quotazione: </span>
            <strong><%= l @stock.quotation_date, format: "%d-%m-%Y" unless @stock.quotation_date.nil? %></strong>
          </li>
          <li class='list-group-item'>
            <span>Data check: </span>
            <strong><%= l @stock.quotation_check, format: "%d-%m-%Y %H:%M" unless @stock.quotation_check.nil? %></strong>
          </li>
          <li class='list-group-item'>
            <span>Dividendo: </span>
            <strong><%= @stock.dividend %></strong>
          </li>
          <li class='list-group-item'>
            <span>Mercato: </span>
            <strong><%= @stock.market %></strong>
          </li>
        </ul>
      </div>
    </div>

  </div>
</div>