config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_items, :path => 'portfolio'
  get 'stock_signal_checks/index'
  get 'stock_signals/index(/:check_id)', to: 'stock_signals#index', as: 'stock_signals'
  get 'stock_signals/full(/:check_id)', to: 'stock_signals#full', as: 'stock_signals_full'
  get 'stock_signals/compact(/:check_id)', to: 'stock_signals#compact', as: 'stock_signals_compact'
  resources :stocks
  root to: 'stock_signals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord
  belongs_to :user
  belongs_to :stock
  attr_accessor :stock_ids

  validates :stock, presence: true
  validates :stock_ids, presence: true
  validates :quantity, presence: true
  validates :avg_stock_value, presence: true
  validates :sell_stock_value, presence: true, if: :closed?

  def sell_stock_value
    return self[:sell_stock_value] if closed?
    return stock.quotation if stock && stock.quotation
    nil
  end

  def profit_loss
    (sell_stock_value-avg_stock_value)*quantity rescue 0
  end

  def closed?
    closed
  end

  def closed_text
    return "chiusa" if closed?
    "aperta"
  end

end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource


  # GET /portfolio_items
  # GET /portfolio_items.json
  def index
  end

  # GET /portfolio_items/1
  # GET /portfolio_items/1.json
  def show
  end

  # GET /portfolio_items/new
  def new
    @portfolio_item = PortfolioItem.new
  end

  # GET /portfolio_items/1/edit
  def edit
  end

  # POST /portfolio_items
  # POST /portfolio_items.json
  def create
    @portfolio_item = PortfolioItem.new(portfolio_item_params)
    @portfolio_item.user = current_user

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_items/1
  # PATCH/PUT /portfolio_items/1.json
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_items/1
  # DELETE /portfolio_items/1.json
  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_items_url, notice: 'Portfolio item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_item
      @portfolio_item = PortfolioItem.find(params[:id])
      @portfolio_item.stock_ids = [@portfolio_item.stock_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_item_params
      p = params.require(:portfolio_item).permit({:stock_ids => []}, :avg_stock_value, :quantity, :sell_stock_value, :notes, :closed)
      p[:stock_id] = p[:stock_ids].first unless p[:stock_ids].blank?
      p
    end
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
  def display_profit_loss n
    k = (n >= 0)? 'profit' : 'loss'
    content_tag :div, class: k do
      number_with_precision(n, precision: 2, strip_insignificant_zeros: true)
    end
  end
end

app/views/portfolio_items/_form.html.erb
<%= bootstrap_form_for(@portfolio_item, layout: :horizontal, label_col: 'col-sm-2 col-form-label', control_col: 'col-sm-10') do |f| %>

      <%= f.collection_select :stock_ids, Stock.order('symbol asc'), :id, :name,
        {label: 'Azione', include_hidden: false}, {multiple: true, class: 'select2'} %>

      <%= f.number_field :avg_stock_value, label: "Prezzo di carico", step: 0.0001 %>
      <%= f.number_field :quantity, label: "Quantità", step: 1 %>
      <%= f.number_field :sell_stock_value, label: "Prezzo di vendita", step: 0.0001 %>
      <%= f.text_area :notes, label: "Note" %>
      <%= f.form_group :closed, label: { text: "Stato" } do %>
        <%= f.check_box :closed do %>
          Chiusa
        <% end %>
      <% end %>


  <div class='form-group row'>
    <div class='col-sm-2'></div>
    <div class='col-sm-10'>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= back_link class: 'btn btn-default pull-right' %>
    </div>
  </div>

<% end %>

app/views/portfolio_items/edit.html.erb
<div class='container-fluid'>
  <h3 class='pt-4'>Modifica posizione</h3>
  <div class='row'>

    <div class='col-md-3'>
      <div class='list-group'>
        <%= link_to portfolio_items_path, class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :list) %> Portfolio
        <% end %>
        <%= link_to @portfolio_item, class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :eye) %> Mostra posizione
        <% end %>
        <%= link_to @portfolio_item, data: {confirm: 'Are you sure?'},
              method: :delete, class: 'list-group-item list-group-item-danger list-group-item-action' do %>
          <%= icon(:fas, :trash) %> Cancella posizione
        <% end %>
      </div>
    </div>

    <div class='col-md-9'>
      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/portfolio_items/index.html.erb
<div class='container-fluid'>
  <h3 class='pt-4'>Portfolio</h3>
  <div class='row'>
    <%= content_tag 'table', id: "portfolio", class: 'table table-striped datatable' do %>
      <thead>
        <tr>
          <th>Id</th>
          <th>Azione</th>
          <th>Prezzo di carico</th>
          <th>Quantità</th>
          <th>Quotazione/Prezzo di vendita</th>
          <th>Profitto/Perdita</th>
          <th>Stato</th>
        </tr>
      </thead>
      <tbody>
        <% @portfolio_items.each do |portfolio_item| %>
          <tr>
            <td><%= link_to portfolio_item.id, portfolio_item %></td>
            <td><%= link_to portfolio_item.stock.name, portfolio_item.stock %></td>
            <td><%= number_with_precision(portfolio_item.avg_stock_value, precision: 5, strip_insignificant_zeros: true) %></td>
            <td><%= portfolio_item.quantity %></td>
            <td><%= number_with_precision(portfolio_item.sell_stock_value, precision: 5, strip_insignificant_zeros: true) %></td>
            <td><%= display_profit_loss(portfolio_item.profit_loss) %></td>
            <td><%= portfolio_item.closed_text %></td>
          </tr>
        <% end -%>
      </tbody>
    <% end %>
  </div>
  <hr>
  <%= link_to new_portfolio_item_path, class: 'btn btn-primary btn-lg' do %>
    <%= icon(:fas, :plus) %> Nuova posizione
  <% end %>
</div>

app/views/portfolio_items/new.html.erb
<div class='container-fluid'>
  <h3 class='pt-4'>Nuova posizione</h3>
  <%= render 'form' %>
</div>

app/views/portfolio_items/show.html.erb
<div class='container-fluid'>
  <h3 class='pt-4'>Posizione</h3>
  <div class='row'>

    <div class='col-md-3'>
      <div class='list-group'>
        <%= link_to portfolio_items_path, class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :list) %> Portfolio
        <% end %>
        <%= link_to edit_portfolio_item_path(@portfolio_item), class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :wrench) %> Modifica posizione
        <% end %>
        <%= link_to new_portfolio_item_path, class: 'list-group-item list-group-item-action' do %>
          <%= icon(:fas, :plus) %> Nuova posizione
        <% end %>
      </div>
    </div>

    <div class='col-md-9'>
      <div class='card'>
        <div class='card-header'>Dettagli</div>
        <ul class='list-group list-group-flush'>
          <li class='list-group-item'>
            <span>Azione: </span>
            <strong><%= @portfolio_item.stock.name %></strong>
          </li>
          <li class='list-group-item'>
            <span>Prezzo di carico: </span>
            <strong><%= number_with_precision(@portfolio_item.avg_stock_value, precision: 5, strip_insignificant_zeros: true) %></strong>
          </li>
          <li class='list-group-item'>
            <span>Quantità: </span>
            <strong><%= @portfolio_item.quantity %></strong>
          </li>
          <li class='list-group-item'>
            <span><%= @portfolio_item.closed? ? "Prezzo di vendita:" : "Quotazione" %> </span>
            <strong><%= number_with_precision(@portfolio_item.sell_stock_value, precision: 5, strip_insignificant_zeros: true) %></strong>
          </li>
          <li class='list-group-item'>
            <span>Profitto/Perdita: </span>
            <strong><%= number_with_precision(@portfolio_item.profit_loss, precision: 2, strip_insignificant_zeros: true) %></strong>
          </li>
          <li class='list-group-item'>
            <span>Note: </span>
            <strong><%= @portfolio_item.notes %></strong>
          </li>
          <li class='list-group-item'>
            <span>Stato: </span>
            <strong><%= @portfolio_item.closed_text %></strong>
          </li>
        </ul>
      </div>
    </div>

  </div>
</div>